### ISSUE TITLE
Feature request: zip old rolling file

### ISSUE THREAD

**Issue by adoris123** [cocowalla/serilog-sinks-file-gzip#1]
It will be nice if only old files are gzipped and current log files leaves as is, unzipped. As option for existing functionality.
Thanks for super plugin!

**Comment by cocowalla** [comment]
Hmm, so, I'm not sure if that's going to be possible using FileLifecycleHooks.

There are 2 ways in which you can do compression:

1. Streaming compression, as the file is written
2. Compressing already written, rolled, closed files

This plugin implements the first one, as `FileLifecycleHooks` enables wrapping the original stream. You can find some discussion about this over in [this issue](https://github.com/serilog/serilog-sinks-file/issues/48).

**Comment by cocowalla** [comment]
Just a note to say there is now also another plugin available, [serilog-sinks-file-archive](https://github.com/cocowalla/serilog-sinks-file-archive). It doesn't work *quite* how you describe, but it is similar.

As files drop out of retention, Serilog's rolling file mechanism usually deletes them, but this `serilog-sinks-file-archive` lets you archive them instead (copy and/or compress).
