### ISSUE TITLE
Library dependencies?

### ISSUE THREAD

**Issue by Numpsy** [cocowalla/serilog-sinks-file-gzip#2]
Hi,
I tried installing serilog.sinks.file.gzip into a .NET Core 3.1 test app, and got quite a few extra dependencies requested:

![image](https://user-images.githubusercontent.com/1178570/85807638-651bb900-b74a-11ea-907c-46812c23d204.png)

Was just wondering if the System.IO.Compression dependency is really necessary when targetting something as recent as .NET Standard 2.1?
(Similar situation to https://github.com/serilog/serilog-sinks-file/issues/139, except the dev versions of the File sink have a .NET Core 3.0 target that doesn't have extra dependencies)

**Comment by cocowalla** [comment]
Hi! Thanks for raising this - I've just pushed a new version that removes the `System.IO.Compression` for more modern versions (only still needed for `netstandard1.6`) 🚢

**Comment by Numpsy** [comment]
thanks
